logging:
  level:
    org.dontstw.eventfactory: debug
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    platform: dev
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML5
  h2:
    console:
      enabled: true
      path: /h2-console